---
config:
  theme: mc
---
mindmap
((AIChat))
  OpenRouter + Models
    (Ai Agent LangGraph)
      Eliza character Module
      Langfuse telemetry
  Statistics
    GoogleAnalytics
  ClerkAuth
    TarifPlans
      StripePayment
    UserProfile
      Credit Balance
      Settings
      ChatHistory+Supabase
  ChromeExtension
  Recognise voice system

