journey
    title Chat flow
    section Message flow
      User write message: 5: User
      Ai assistant answer: 5: AI
      Tokens quantity update: 1: Backend

    section Payment flow
      Tokens run out: 1: Frontend
      User click to tokens sign: 5: User
      FE Shows pricing plans: 3: FE
      User upgrade plan: 5: User
      Tokens for user update: 5: BE
